### Ping
{{local}}/
Content-Type: application/json
X-GitHub-Event: ping

< ping.json

### Push
{{local}}/
Content-Type: application/json
X-GitHub-Event: push

< push.json

### Delete branch
{{local}}/
Content-Type: application/json
X-GitHub-Event: push

< delete-branch.json

### Open pull request
{{local}}/
Content-Type: application/json
X-GitHub-Event: pull_request

< pr-open.json

### Comment on pull request
{{local}}/
Content-Type: application/json
X-GitHub-Event: issue_comment

< issue-comment.json

### Comment on pull request with code link
{{local}}/
Content-Type: application/json
X-GitHub-Event: pull_request_review

< pr-comment.json

### Start workflow
{{local}}/
Content-Type: application/json
X-GitHub-Event: workflow_run

< workflow_run_in_progress.json

### Complete workflow successfully
{{local}}/
Content-Type: application/json
X-GitHub-Event: workflow_run

< workflow_run_completed_success.json

### Complete workflow with failure
{{local}}/
Content-Type: application/json
X-GitHub-Event: workflow_run

< workflow_run_completed_failure.json

### Publish release
{{local}}/
Content-Type: application/json
X-GitHub-Event: release

< release-published.json