### Ping
{{local}}/
Content-Type: application/json
X-GitHub-Event: ping

< ping.json

### Push
{{local}}/
Content-Type: application/json
X-GitHub-Event: push

< push.json

### Open pull request
{{local}}/
Content-Type: application/json
X-GitHub-Event: pull_request

< pr-open.json

### Comment on pull request
{{local}}/
Content-Type: application/json
X-GitHub-Event: issue_comment

< issue-comment.json

### Comment on pull request with code link
{{local}}/
Content-Type: application/json
X-GitHub-Event: issue_comment

< pr-comment.json