// Code generated by rscli. DO NOT EDIT.

package config

type configKey string

const (
	AppInfoName = "app_info_name"
	AppInfoStartupDuration = "app_info_startupDuration"
	AppInfoVersion = "app_info_version"
	DataSourcesPostgresHost = "data_sources_postgres_host"
	DataSourcesPostgresName = "data_sources_postgres_name"
	DataSourcesPostgresPort = "data_sources_postgres_port"
	DataSourcesPostgresPwd = "data_sources_postgres_pwd"
	DataSourcesPostgresUser = "data_sources_postgres_user"
	ServerRestAPICertPath = "server_rest_api_cert_path"
	ServerRestAPIKeyPath = "server_rest_api_key_path"
	ServerRestAPIPort = "server_rest_api_port"
	ServerTgAPIKey = "server_tg_api_key"
	WebhookHostURL = "webhook_host_url"
)
