name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push image
        run: |
          REPONAME=echo ${{ github.event.repository.name }} | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PWD }} ${{ secrets.REGISTRY_HOST }}
          docker build -t ${{ secrets.REGISTRY_HOST }}/${{ REPONAME }}:$GITHUB_SHA -t ${{ secrets.REGISTRY_HOST }}/${{ REPONAME }}:latest .
          docker push ${{ secrets.REGISTRY_HOST }}/${{ REPONAME }}:$GITHUB_SHA
          docker push ${{ secrets.REGISTRY_HOST }}/${{ REPONAME }}:latest
 
